<?php

namespace App\Jobs;

use App\Jobs\Job;
use App\Models\Transcript;

use App\Http\Controllers\TranscriptionController;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Http;


class PostAudioToINVOXMD extends Job
{

    protected $audio_path;
    protected $audio_id;

    /**
     * Create a new job instance.
     *
     * @return void
     */
    public function __construct($path, $id)
    {
        $this->audio_path = $path;
        $this->audio_id = $id;
    }

    /**
     * Execute the job.
     *
     * @return void
     */
    public function handle()
    {
        // Se envía el audio al servicio de transcripción
        //$invoxmd_service = new TranscriptionController();
        //$invoxmd_service->postAudioINVOXMD($this->audio_path, $this->audio_id);


        $API_INVOXMD_URL = env('API_INVOXMD_URL');
        $API_INVOXMD_USERNAME = env('API_INVOXMD_USERNAME');
        $API_INVOXMD_PASSWORD = env('API_INVOXMD_PASSWORD');

        $response = Http::asForm()->post(
            $API_INVOXMD_URL . '/Transcript/v2.6/Token',
            [
                'grant_type' => 'password',
                'username' => $API_INVOXMD_USERNAME,
                'password' => $API_INVOXMD_PASSWORD
            ]
        )->json();

        $token =  $response['access_token'];

        $API_INVOXMD_URL = env('API_INVOXMD_URL') . 'Transcript/v2.6/Transcript?username=nicolasenrique01';


        //$audiofile = File::get('/var/www/html/TFG_MobileApp_API/storage/app/40/masde2mb.wav');

        $response = Http::asForm()->withToken($token)->post(
            $API_INVOXMD_URL,
            [
                'Format' => 'WAV',
                'Data' => 'UklGRuzvAgBXQVZFSlVOSxwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZm10IBAAAAABAAEAgD4AAAB9AAACABAARkxMUqgPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABkYXRh9N8CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEA/f8NANz/hP8EAI8AnABmACMA9v/g/9f/v/+F/1v/cP+7/97/8/8uAFMANwAJAAkAPgBoAHYAaQBYACwA/v/q/+v/BAAnAC0ALwAdAPz/wf+U/57/0v/3/wYABQD+/9n/r//E/73/qf+s/7X/vP/C/7v/2f/p/9P/xP++/8r/1f/W/+P/DgAhAAUA3//V/+L//v8gADoAQwBLAGAAawB0AKAAzQDdAPUAAgHgALMAiQBpAHIAdwB/AEkA9f/G/8L/3P/O/8f/zf+6/7T/t//A/8v/yv/I/8b/u/+x/8X/2v/c/+P/8P8EAAIABAAQAAsA/v/y/+X/1f/d/8T/gf9N/zr/MP8W/wf/Hf9R/2P/Of8Y/y7/Vv9//5b/o//H//H/+//q//b/FAAtAB8A/f8UAFEAdAB4AHMAXgAnAO7/2f/o/wMAGwAlACMAFAD8/9n/zf/t/xwAMgA8ACoAIQA4AFMAagB7AIoAmQCjAJgAgwCdAMYAvgCSAHQAZABLACkAEQARABQAGgAlAC0AJgApACMAEgAUACUAMQAzADsAPQBCAFMAWQBVAGIAewCMAHwAYgBkAHAAegBsAEUAKQBCAE8ARAAzAAwA3v++/8b/+v8pACAACQADABcAIgAZAA8A/f/0/wQAEwASAAYA5P/H/8j/2f8IADkAOgAaAPD/3v/W//r/JQA5AEQAVABAAPv/vv+h/7j/7v8bADIAMQAhAB8ALwA/ADEACQDa/9r/AAAdAAoA4//s/+z/tv+F/3//kf+y/8D/rf+U/5T/j/+O/57/uP/f/+T/0P/S/9r/3P/S/9X/8P8OACsANwAwABMA6P/Z/9//9f8RAPn/4v+w/2X/Nf8v/0D/Xf+A/4n/kv+M/3T/jf+0/9P/3f/C/5n/d/9t/4H/k/+M/3n/UP8V//r+Fv81/0r/bP+D/37/af9i/3D/fv+0/8n/tf+//9D/4P/5/xAAKwBIAEwAQQBGAEYAHQASABwAEQAOABIAGgASAAkACAD5//r/CAAcABEA9//x//L/AAD0/+7/CAAJAMf/m/+e/7//6P8OAA8A9v/l/9D/2/8ZAGAAaABDABMA+P8VACwAQwBfAIEAfABRAC0AGwBAAIgAuACsAJ4AxwDcALcAjwCIAKYA2gDaAMMAqgCeAJEAbQB5AJIAnACcAKsAxwDFAKYAmACdAJUAiABJAAYA4/+1/5n/k/+x/8j/wf+x/5r/g/+H/53/vf/J/8D/xv/n/xEANgBRAEAAJAAFAOD/4//3//7/6v/d/8H/q//B/+D/+v8jADQAIQAIAPv//v8GAA8ALgBCAGUAbgB0AIEAnQCYAGoASwAlAA4AFAD//+P/4v/k/+r/3//g////CwAYADYANQAbABYAJAAvABEA5f+8/63/2f/z/9//y//R//j/HwAuABoAHAAvAEsAVQA4ADkATwBGADUAHwAGAAYAAADe/9D/3v/I/4n/Vf9E/1X/V/9i/2X/WP9g/2v/gv/D//L/1v+s/67/2f8MACIAEgACAAQA///n/9f/5P/+/wIA9f/0//3/+//t//f/DAAKAAIA8//4/wsADgAeAB4ACAD5//3/LgBjAIQAhwBRABMA8v8VAEcAQAAbABMADADq/9L/6v8DAAIA7//s/+b/3P/f/8z/r/+W/5P/lf+h/8j/1f/N/7j/q//Q//f/BgA3AHIAjwCLAFUANQA8AD8AKQAQAOP/rP+Y/5//z//w/+r/1P/I/9P/z//L//H/DADu/9T/y/++/8r///8uADsALAArAFQAfgB9AGcAZQBrAF8APgAzADAAHwAFAPX/6//D/5T/f/+N/6z/xv+w/5D/h/+U/5P/hf9//4T/nv+x/6v/p/+7/83/xv/g/wQALgBIAEQALwAfACEAGQAKABwARQBjAGAAPwAgACUANQAbAAIA7f/3//P/1//H/9n/+f/7//P/7v8GAAYA9v/x/+n/1P/C/7v/y//t//n/4P+5/63/wf/f//T///8NABUA/f/f//D/GwAvABoACAAHABsALQBCAEAAKgAyAFcAfwCNAIYAfwCLAKEArgCtAIcAZgBqAFoAJQDn/6L/V/86/1D/hv+p/5r/gv9w/2T/dP+d/8v/8//y/9v/5v8GAA8ADQAZACgAJwAUAAYAHQBGAFUAWgBVADcAIQATAAYAHwAlABAADQAmADoAPABMAF0AYgBZAFEASwBRAGMAgwCBAFkARgA4ACAAKgBCADkAIgAXAAoA9//s/9f/wP+q/5r/r//r/xEA/P/J/7H/rf+3/83/3v/w////8P/e/+r/CQAIAOn/w/++/9T/2P/J/8v//v86AD8AGAACABMANABMAG4AgwB5AF8AOwA1AFwAawA6ABYAIQA/ADsAGQAhAEQAVQBRAEAAOgAyACQA8P/L/6b/dv9M/1T/hP+r/8X/v/+2/7P/wP/S/+X/AwAMAAcAFAAzADwALQAyAC8AGwA4AHwAqQCgAKMAqgCmAJcAggBnAF4AbABPABUA/////+r/0//J/9j/3P/E/6n/n/+i/57/mv+Y/5z/nP+Q/57/t//A/8P/xf/B/9r/9//z/+T/6f/r/93/zf/V/+n/BQAPAAUACwAOAAYA+f/n/+j/5v/S/+T/6f/p/9v/1f+8/6X/o/+r/6n/nv/B/+//8P/Q/6H/k/+y//P/DwDf/7H/tv+7/7b/vf+y/5r/ff+C/57/uf+1/5j/jP+c/7f/qP+K/4v/tv/k//3/AQD5/+H/yv/d/xQARgBoAFAAHwAJACYAUQBfAD4ACgDz/xMAJQAOAO3/xf+7/7v/y//z/wYA3f+0/63/tf+//7n/qv+T/47/sv/e//7/BwAZAD8AXwBPABQA//8CAA4AHwAZABQAJwA4ADUANgBDADkADgAJABcAHwAZAAcAEgAZAA8AEgApADwARABHAFYAcQCFAI8AjwCJAH4AbABFAAsA3P/Y//H/8v/m//H/7//m/9z/yv/P/+v/CwAqAC8AEgAEAPv/DgAxAD4AJgATAAsAIAA6ADMARgBgAGEAcABxAHEAfgCWAKwAmgB2AGEATgAyACIAMQBAAEoARQAvADYANQBBAEkAMgBEAFUASAA8AD4AagB/AHsAbQBZAEEAOABHAEYAQwBJAE4AQAA3ADQALAAUAPL/1//J/8P/rv+o/8n/1//B/7j/zv/y/wYABwAZADIAPQBGAEkAOgAWAOv/y//O/+j/8v/s/+z/+v8DAPr/9f8DAB4AKQAlADQAJgD3/8n/x//i/+z/8v/s/+3/DgAbAPv/x/+d/4z/eP+D/7H/rv+a/47/j/+V/4//mv+c/5f/sf/O/8r/0v/t//H/3v/C/7f/zf/p/83/t//N//D/AQDy/9H/r/+n/5v/nv+1/8b/uv+j/6//8P82ADUABwDg/+L/BwAXABQABgDn/9P/xP+x/7z/zP/U/9f/wf+//7z/pf9//3n/qf/h//T/0f+j/63/1P/9/wYAAAD5/97/6v8UAB8AHAAQAO3/4f/r/+//5//d//v/GwAfAA4AAwAWACcAKQAbAAoA8//F/8H/6/8cADsAQgA8ADsAOQA3AEQAYABpAGEAOgAjACoAFQANACMANQA4AEIAOgAuABUA8v/d/8z/wf/H/93//f8XAAwA8//h/+b/7//u//b/BwD+//D/8//z//X/9P/X/9b/wv+3/+L/+//s/93/6//v/9P/sv+n/6D/nf+f/6X/v//X/97/5v/4/xMAHQAJAAUA9f/f/+T/8P/t/+z/6P/V/9T/yf+5/73/zv/k/+7/8//x/xUANgBQAFcAXwBxAHAAcwBsAFoAXQBtAGEAOAATAPz/+/8DAPT/8P/u////OgBQADoA/v/T/8f/z//x/wQA6P/b//H/CAAbACMAHAAcAB8AHgAYABIALABKAFEAVABsAHsAVwAiAAsAHQA+AEcATABSAFAATgA/ACoAQQBXAEkAPQA/AEUATwBQAEIAGgDT/6//vP/J/+f/DQAbACAAIwAwAE0AaAB4AIMAsADhAN8AwwCrAJ8AlABnADsAJQAqACMA+P/f/93/zv+4/7X/2v8GADYAYgCAAKkAzwDgAN4A1QCwAIwAeACHAKEAlQB1AFgAKAD4/9X/yP/b/+P/2f/t/+v/3v/G/6X/m/+o/7P/1//V/63/lf+n/9r/+f/u/8v/zf/g/+z/BgAoACsACwDr/+X/8P/h/7L/kf+d/67/qP+d/53/ov+2/9j/3P/q/wUAFgAaABwANwBOAFEATwBLAFIAUABEADoAOQAxABwACgAIAAIA8v/e/7v/sv+j/4H/bP96/4f/av9J/zD/IP8Z/wH/7/4J/z7/SP9H/zb/G/8Z/y//Xv+R/6b/tP+y/63/tf+r/6L/p//Q//v/CwAJAPT/0//t/ywARAAYAOn/0P/G/9X/2v+6/43/av9f/2T/ZP9D/yL/K/84/0X/S/86/xn/8f7Z/uz+If9N/0r/IP8M/y7/Yv+O/6X/nf+f/9j/IAA9ADQALQA2ADsARgBaAGsATgApACEAMgBQAEEA/P/e/+v/IQBRAFwAXQBTAFAAaACEAIMAZwA/ABgACAAJAPv/9//2/+3/4//b/73/mv+R/6z/xP/R/87/vP+l/7f/4f8nAFQAUQA9AEUAYACEAJoAnACZAIUAfACHAJEAiQBoAEAARwBsAIwAoACjAI8AiQCiALUAwgC7AKwAqwCoAK4AuQC8AKwAmQB3AHYAeABlAE8AWQBuAGkAcwB6AGUATgAqAAwAJABTAF4AUwA+AEAAbwC1AMkArwCIAFEARgBzAJkAqQCgAIUAbABuAGYAYABaAFsAawBrAE0AOgA/AEcAYQB0AIEAdwBoAEsAQgBYAGwAfwBiAD0AQQBdAHUAaABPAC0ACQDn/+z/CQAOAPr/v/+U/6L/t//I/9T/5f8PADEAQwBWAFIAawCQAKMAigBgAEQARwB1AKgAuwCsAIoAaQBSADsASQBLADsAJQAPAAUA8f/p/9//vf+N/1z/PP9A/2n/jv+l/7D/wP/T/+r/9P/v/////P/e/8P/t/+v/7n/zf/w/+L/o/9W/zn/U/+C/57/kv94/27/j/+3/9b/4P/d/8D/rf/I//L/FwAYAOz/3v8DAAgA3v+v/5H/nf+i/4r/Vv8i/x3/F/8I/xb/Qv9O/zP/Cv/w/uP+z/7L/tb+9P4B/xn/Kv9B/2H/eP+G/5n/tv/D/6//kP9h/0P/If/p/rX+o/60/tz+7v7v/hH/Wv+b/83//P8TAPz/1//d/wAAFAAAAM//s/+O/3D/a/9+/5L/i/90/2f/Yv9l/3f/iv+S/53/pf+M/2D/Qv9S/47/uv+0/6v/hv+X/+z/MwBNAE8ASABTAFsAbgCrANsA4gDaAOcA8ADcAM4A1QDmAPEA/gAUASQBEAHwAM8AugCcAF8ALQAcABgANgBKAEUARgAjABEALABPAHIAgwBqAEgANwBAAGwAoADKANIAvgCtAK8AwgDWAL8AlwBxAHgAlQCaAKwAsACvAJsAlgCVAI0AhwCMAJ8AlwByAGEARwBJAGMAbgBeADMAGwAdADwAYgCCAIsAfwCEAKgAsQCUAHcAXQBOADYAFwAFAAwAIwA1AEEAIADj/8b/3/8SACYAJAD2/73/n/+k/63/wf/U/7L/qf/X/xIAXwCiAMYA4wDmAL0AkgB0AH4AmAClAIYARQAJAM//vf/P/9z/yf+h/3b/Wv9W/1b/ef+q/6X/c/9G/0r/i//W/xoANAA4AF4AiQC8APYADQHgAIIAPwBBAFQAUwBWAFsATwArAAEA/v/3/9//8f8IAAMA4f+0/73/6f8GACAAEQDO/5H/cf+F/8L/x/+b/27/VP9L/2X/l//M/9X/vf+a/5P/p//D/+f/9v/3/+r/zf+u/7D/sP+w/8T/3v/m/77/mv+g/8D/uv+Y/1H/Hv8i/0L/ev+g/5z/mv+e/6z/wP/A/77/uf+h/43/iP+g/7f/x/+4/5//uv/I/7r/nv+M/5j/q/+w/6//sP+y/7f/uf+m/33/XP9g/4z/zf8AAOr/qP9x/2T/cP9x/4T/n/+s/6T/mf+3/9f/3//J/8H/z//D/67/n/+a/5X/jv+U/6r/tP+4/8//9P8jACYA9v/L/67/3v8dAD0AOAAMANv/v/+p/63/wf/B/6v/jf+N/6//zv/p//H/6//6//7/AgD5//X/EQBEAEYAIAALABQAGgAeACAAGADo/6//r//R/wQAEwD5/9b/uf+0/+T/IwBFAFsAWwBKAE8AWwBdAHEAiQCYAIMAbwBmAGgAYwBWAFgAYgB9AI0AcwBKAEsAbQCKAIkAVwAVAAYAOQBgAGYAZABdAF0AZgB8AJYAsQC8ALAAnACnAM0AzgC5AJwAeABOACEADwAmAFoAoQCsAKQAhwBSADAAJAA2AHIAfQBeAEsAWQCPAM8A9QAHAQYB4QC8ALwAqACjALgAvgCtAIgAbwBgAGAAVQBXAFsAZgBbADgAPwBEAG4AlABtAD0AIwAuAGIAtwDJAKYAdgBTAEwAKQAeAB4ADwD7/+v/BwBAAFYAOwAsABkAIgA6AEUAWQBcAGMATwBCAEEAXgCdAKoAkQBfAB4A3v/R//v/FQDq/6X/Zv9B/zn/Uv9n/27/f/94/1D/Of9e/5b/wv/n/+T/yf+u/6//0/8RADwAPgAkAPz/8v/q/9z/3//a/8D/fv9W/2z/mf/Q/+//4f+p/4v/n//Q/xMACADU/6v/cv9A/z3/WP9p/1D/Gf8A/+f+yP6v/sz+8/4A/+X+y/7R/uH+8/77/gb/B/8K/yP/Sf98/43/d/9V/07/Rf87/1n/VP8s/xn/GP8d/xj/+v70/gb/H/8y/yr/P/9D/zL/Tf9m/2n/Yv9r/2z/lf+9/8v/yP/J/+X/0f+4/7r/s/+f/3n/Yf9c/3j/lP+h/6f/kf95/3v/jf+V/7X/0//W/8j/u/+x/7f/0P/o/wsAKAAyADgALAAlAD0AcACOAKUAqACkAKEAmQCJAHsAYQBeAGcAXgA7ABAA9f/q/+7/DQA7AFEAaABVADgAHQApADcAQwBfAH4AtADMANkACAEqAScBHgEVASUBMAEcAfYA6wDkAM8AvACsAJMAogCuAKcApACcAJ4AmwCaAJsAsgC3AMgA0gDaANkA6wDwAOcA5wDsAOEAxwC5AKMAmACfAKYAoQCKAGoAWABaAHoAjwB1AFUAQQAjACEALAAwAEoAeACTAJEAhACGAIcAqQDaAPwAAQH5AM8AzwDgAOEAsQCBAFcAWwBqAHsAiQB7AIMAggBXADoAPAA/ADMAGwDo/9L/0f/w//f/4P/o//7/CgD6/+n/8P/+/xoALgA1ADsAOAAdABIALwAnACkAGwDa/8X/xf/c/+X/0//f',
                'FileName' => 'nuevo_audio'
            ]
        )->json();



        Transcript::create([
            'id' => '3',
            'uid' => Str::random(32),
            'status' => 'Transcribiendo',
            'progress' => '0',
            'start_date' => null,
            'end_date' => null,
            'text' => $response['Text'],
            'id_audio' => 750
        ]);

    }
}
